### PR TITLE
Add ecs deploy workflows

### PR DESCRIPTION
**Pull request by PaulJKim**
#### Summary of changes
This PR adds GitHub Actions workflows for deploying Signs UI to ECS

### CODE REVIEW

**Comment by PaulJKim** [comment]
@losvedir mainly adding you here because I noticed there are some secrets in the Dockerfile and EB workflow called `secrets.ERL_COOKIE` and `secrets.SECRET_KEY_BASE`. I'm unclear on what these are for and would we still need them in the ECS workflow?

**Comment by PaulJKim** [comment]
@losvedir mainly adding you here because I noticed there are some secrets in the Dockerfile and EB workflow called `secrets.ERL_COOKIE` and `secrets.SECRET_KEY_BASE`. I'm unclear on what these are for and would we still need them in the ECS workflow?

**Comment by PaulJKim** [comment]
Adding @cmaddox5 since you said you didn't have too much on your plate at the moment 😄

**Review by cmaddox5 — APPROVED** [review]
This looks good to me! I don't have a ton of experience with this, but comparing this to ECS deploy workflows that I know work currently, this should do the trick.

**Comment by PaulJKim** [comment]
Thank you for clarifying that! I think it makes sense to move those configs to Terraform/the elixir releases in a separate PR since it seems like making a change to the releases would affect any potential deploys we would have to make in the meantime to EB.

For now, I'll just add them to the workflows like they were in the EB deploy workflow. Lmk if you think otherwise though!

**Pull request merged**
