### PR TITLE
feat: SignGroupsChannel Handles Alert Data

### PR DESCRIPTION
**Pull request by mkennedm**
#### Summary of changes
**Asana Ticket:** [🔀 Fill in sign_groups channel handler stub](https://app.asana.com/0/584764604969369/1200222628914563)

The `SignsUiWeb.SignGroupsChannel.handle_in` function rearranges input data to match `SignsUi.Config.State.update_sign_configs` type spec.

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes (compare on Splunk: [staging](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-dev%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840769.3874970) vs. [prod](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-prod%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840745.3874956))

### CODE REVIEW

**Comment by losvedir** [comment]
This doesn't yet meet the acceptance criteria, in particular this one:

> Creating a sign group on the frontend still works. That is, the form can be used to select some zones and some custom text and a date, "Apply" is pressed, and then the saved data appears in the "index" listing of the component.

What I mean by 'the saved data appears in the "index" listing of the component' is that after you click "Apply", it looks like this:

Screen Shot 2021-06-08 at 10 24 22 AM

You can see that behavior yourself by using the Sign Groups form on the `master` branch.

In your PR here, when you click "Apply" it no longer shows the data. That's because you removed the `SignsUiWeb.Endpoint.broadcast!` call (which is correct) but have not yet passed that data into `SignsUi.Config.State`.

**Comment by mkennedm** [comment]
> This doesn't yet meet the acceptance criteria, in particular this one:
> 
> > Creating a sign group on the frontend still works. That is, the form can be used to select some zones and some custom text and a date, "Apply" is pressed, and then the saved data appears in the "index" listing of the component.
> 
> What I mean by 'the saved data appears in the "index" listing of the component' is that after you click "Apply", it looks like this:
> 
> Screen Shot 2021-06-08 at 10 24 22 AM
> 
> You can see that behavior yourself by using the Sign Groups form on the `master` branch.
> 
> In your PR here, when you click "Apply" it no longer shows the data. That's because you removed the `SignsUiWeb.Endpoint.broadcast!` call (which is correct) but have not yet passed that data into `SignsUi.Config.State`.

I tried a bunch of things including copying the lines I added in `lib/signs_ui_web/channels/sign_groups_channel.ex` to `SignsUi.Config.State.update_sign_groups`, `SignsUi.Config.State.handle_call` and `SignsUi.Config.State.save_sign_group_changes`. Nothing worked. How do I get the two files `lib/signs_ui_web/channels/sign_groups_channel.ex` and `lib/signs_ui/config/state.ex` to interact with each other?

**Comment by losvedir** [comment]
> How do I get the two files `lib/signs_ui_web/channels/sign_groups_channel.ex` and `lib/signs_ui/config/state.ex` to interact with each other?

You need to call `SignsUi.Config.State.update_sign_groups(...)` from within `SignsUiWeb.Channels.SignGroupsChannel.handle_in`.

**Comment by losvedir** [comment]
Closing in favor of https://github.com/mbta/signs_ui/pull/537.

**Pull request closed without merging**
