### PR TITLE
Upgrade to Elixir 1.9

### PR DESCRIPTION
**Pull request by losvedir**
#### Summary of changes
**Asana Ticket:** none

When looking to upgrade `tzdata` to address the periodic crashes we're seeing in the logs, I saw that our Elixir version was pretty far behind. This PR:

* Upgrades from Elixir 1.6 / Erlang 20 to Elixir 1.9 / Erlang 22
* Upgrades Distillery to the latest version in order to use `mix distillery.release`, since the  command we were using before to build, `mix release`, became a part of Elixir 1.9 natively and works slightly differently.
* Switches from `Poison` to `Jason`, since I was getting `mix dialyzer` errors I couldn't resolve.
* Adds a `setup.sh` script like our other repos, to ensure Semaphore is using the same versions as we are.

#### Reviewer Checklist
- [ ] Meets ticket's acceptance criteria
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Codecov)
- [ ] This branch was deployed to the staging environment and is currently running with no unexpected increase in warnings, and no errors or crashes (compare on Splunk: [staging](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-dev%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840769.3874970) vs. [prod](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3Dsigns-ui-prod%20%22%5Berror%5D%22%20OR%20%22%5Bwarn%5D%22%20OR%20%22CRASH%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-4h%40m&latest=now&sid=1545840745.3874956))

### CODE REVIEW

**Comment by lemald** [comment]
Super pedantic point, but if you're going for Conventional Commits, shouldn't the "install with yarn not npm" commit have a type?

**Comment by losvedir** [comment]
Ah, right. I didn't give it a type because I figured I would have to iterate a bit on getting it to pass CI and do a successful deploy, and that I'd just squash all the commits together at the end (since they're they break the build in the intermediate stages). But then I forgot that and went back to conventional commits for the next ones...

I plan to squash and merge, since I don't like having commits that fail CI, and will use a conventional commit title for the squashed result.

**Comment by losvedir** [comment]
Hm, looks like Codecov isn't running. @paulswartz - can you see if you need to do that installation thing you have access to, for Signs UI?

**Comment by paulswartz** [comment]
> Hm, looks like Codecov isn't running. @paulswartz - can you see if you need to do that installation thing you have access to, for Signs UI?

all set

**Pull request merged**
